import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ul className='flex space-x-4 p-3'>
          <li>
            <a href='/' className='hover:text-orange-600'>home</a>
          </li>
          <li>
            <a href='/doc' className='hover:text-orange-600'>doc</a>
          </li>
        </ul>
        <div>{children}</div>
      </body>
    </html>
  )
}
